pipeline:
  name: HarnessGit
  identifier: HarnessGit
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.GitHarness1
        repoName: ultimate-devops-project-aws
        build: <+input>
  stages:
    - stage:
        name: Pull
        identifier: Pull
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: account.GitHarness1
                    repoName: ultimate-devops-project-aws
                    build:
                      type: branch
                      spec:
                        branch: main
